"""
mailer.py — email the generated brief PDF as an attachment.

Standard library only (no pip install): smtplib + email.message.
Credentials come from the environment, never hardcoded:
  EMAIL_USER          your Gmail address (the sender)
  EMAIL_APP_PASSWORD  a Gmail "App Password" (NOT your real password)

Gmail App Password: Google Account → Security → 2-Step Verification → App Passwords.
Put both in .env (which is gitignored). Never commit them.
"""

import os
import smtplib
from email.message import EmailMessage
from pathlib import Path


def send_email(to_addr: str, pdf_path: str, company_name: str) -> None:
    """Send the brief PDF to `to_addr` as an attachment."""
    # 1. Read credentials from the environment (fail clearly if missing).
    user = os.environ.get("EMAIL_USER")
    app_password = os.environ.get("EMAIL_APP_PASSWORD")
    if not user or not app_password:
        raise RuntimeError(
            "EMAIL_USER / EMAIL_APP_PASSWORD not set. Add them to .env "
            "(use a Gmail App Password, not your real password)."
        )

    # 2. Build the email message (headers + body).
    msg = EmailMessage()
    msg["From"] = user
    msg["To"] = to_addr
    msg["Subject"] = f"Interview prep brief: {company_name}"
    msg.set_content(
        f"Attached is your interview-prep brief for {company_name}.\n\n"
        "Generated by interview-prep-agent."
    )

    # 3. Attach the PDF. Read its raw bytes, then declare its type so the mail
    #    client shows it as a downloadable PDF.
    pdf = Path(pdf_path)
    data = pdf.read_bytes()
    msg.add_attachment(
        data,
        maintype="application",
        subtype="pdf",
        filename=pdf.name,  # the filename the recipient sees
    )

    # 4. Connect to Gmail's SMTP server, secure the connection, log in, send.
    #    Port 587 + starttls() = upgrade a plain connection to encrypted (TLS).
    with smtplib.SMTP("smtp.gmail.com", 587) as smtp:
        smtp.starttls()  # encrypt the connection
        smtp.login(user, app_password)  # authenticate
        smtp.send_message(msg)  # send it

    print(f"📧 sent {pdf.name} to {to_addr}")
